import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bbsimples.settings')

import django
django.setup()

from bb_enxoval.models import City, State
from smart_selects.utils import unicode_sorter

CIDADES = [
"Belo Horizonte",
"Uberlândia",
"Contagem",
"Juiz de Fora",
"Betim",
"Montes Claros",
"Ribeirão das Neves",
"Uberaba",
"Governador Valadares",
"Ipatinga",
"Sete Lagoas",
"Divinópolis",
"Santa Luzia",
"Ibirité",
"Poços de Caldas",
"Patos de Minas",
"Pouso Alegre",
"Teófilo Otoni",
"Barbacena",
"Sabará",
"Varginha",
"Conselheiro Lafaiete",
"Vespasiano",
"Itabira",
"Araguari",
"Passos",
"Ubá",
"Coronel Fabriciano",
"Muriaé",
"Ituiutaba",
"Araxá",
"Lavras",
"Itajubá",
"Nova Serrana",
"Itaúna",
"Pará de Minas",
"Paracatu",
"Caratinga",
"Nova Lima",
"São João del-Rei",
"Patrocínio",
"Timóteo",
"Manhuaçu",
"Unaí",
"Curvelo",
"Alfenas",
"João Monlevade",
"Três Corações",
"Viçosa",
"Cataguases",
"Ouro Preto",
"Janaúba",
"São Sebastião do Paraíso",
"Januária",
"Formiga",
"Esmeraldas",
"Pedro Leopoldo",
"Lagoa Santa",
"Ponte Nova",
"Mariana",
"Frutal",
"Três Pontas",
"São Francisco",
"Pirapora",
"Campo Belo",
"Congonhas",
"Leopoldina",
"Guaxupé",
"Lagoa da Prata",
"Itabirito",
"Bocaiuva",
"Bom Despacho",
"João Pinheiro",
"Monte Carmelo",
"Diamantina",
"Santos Dumont",
"São Lourenço",
"Caeté",
"Santa Rita do Sapucaí",
"Nanuque",
"Oliveira",
"Machado",
"Visconde do Rio Branco",
"Almenara",
"Salinas",
"Igarapé",
"Boa Esperança",
"Andradas",
"Arcos",
"Várzea da Palma",
"Porteirinha",
"Ouro Branco",
"Brumadinho",
"Iturama",
"Capelinha",
"Jaíba",
"Araçuaí",
"Matozinhos",
"Além Paraíba",
"São Gotardo",
"Itamarandiba",
"Piumhi",
"Guanhães",
"Extrema",
"Taiobeiras",
"Ouro Fino",
"Carangola",
"Brasília de Minas",
"Santana do Paraíso",
"Espinosa",
"Minas Novas",
"Novo Cruzeiro",
"Barão de Cocais",
"Pompéu",
"Três Marias",
"Rio Pardo de Minas",
"Carmo do Paranaíba",
"Sarzedo",
"Santa Bárbara",
"Mateus Leme",
"São Joaquim de Bicas",
"Campos Gerais",
"Cambui",
"Coromandel",
"Buritizeiro",
"Mantena",
"Cláudio",
"Santo Antônio do Monte",
"Prata",
"Mutum",
"Eloi Mendes",
"Pitangui",
"Coração de Jesus",
"Nepomuceno",
"São João Nepomuceno",
"Conceição das Alagoas",
"Francisco Sá",
"Belo Oriente",
"São João da Ponte",
"Sacramento",
"Aimorés",
"Juatuba",
"Jequitinhonha",
"Tupaciguara",
"São Gonçalo do Sapucaí",
"Carandaí",
"Jacutinga",
"Ibiá",
"Inhapim",
"Pedra Azul",
"Espera Feliz",
"Buritis",
"Corinto",
"Raul Soares",
"Paraopeba",
"Bambuí",
"Caraí",
"São João do Paraíso",
"Itambacuri",
"Abaeté",
"Monte Sião",
"Conselheiro Pena",
"Manhumirim",
"São José da Lapa",
"Caxambu",
"Itapecerica",
"Camanducaia",
"Carmo do Cajuru",
"Monte Santo de Minas",
"Monte Azul",
"Itaobim",
"Paraguaçu",
"Medina",
"Serro",
"Campestre",
"Carmo do Rio Claro",
"Perdões",
"Muzambinho",
"Monte Alegre de Minas",
"Paraisópolis",
"Barroso",
"Lambari",
"Vazante",
"Lajinha",
"Padre Paraíso",
"Divino",
"Campina Verde"
]

if __name__ == '__main__':
    state = State.objects.filter(acronym="MG")
    cities = City.objects.filter(state=state)
    # city_names = {}
    # for city in cities:
    #     city_names[city.name] = True
    # for city in CIDADES:
    #     if city not in city_names:
    #         print(city)
    #         i = i + 1
    for city in cities:
        if city.name not in CIDADES:
            city.delete()
