import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bbsimples.settings')

import django
django.setup()

from bb_enxoval.models import City, State
from smart_selects.utils import unicode_sorter

CIDADES = [
"Porto Alegre",
"Caxias do Sul",
"Pelotas",
"Canoas",
"Santa Maria",
"Gravataí",
"Viamão",
"Novo Hamburgo",
"São Leopoldo",
"Rio Grande",
"Alvorada",
"Passo Fundo",
"Sapucaia do Sul",
"Uruguaiana",
"Santa Cruz do Sul",
"Cachoeirinha",
"Bagé",
"Bento Gonçalves",
"Erechim",
"Guaíba",
"Cachoeira do Sul",
"Esteio",
"Ijuí",
"Santana do Livramento",
"Sapiranga",
"Lajeado",
"Santo Ângelo",
"Alegrete",
"Santa Rosa",
"Venâncio Aires",
"Farroupilha",
"Camaquã",
"Vacaria",
"Campo Bom",
"Cruz Alta",
"Montenegro",
"São Gabriel",
"São Borja",
"Carazinho",
"Taquara",
"Parobé",
"Canguçu",
"Santiago",
"Capão da Canoa",
"Tramandaí",
"Estância Velha",
"São Lourenço do Sul",
"Osório",
"Canela",
"Santo Antônio da Patrulha",
"Panambi",
"Marau",
"Rosário do Sul",
"Dom Pedrito",
"Itaqui",
"Rio Pardo",
"20px Charqueadas",
"Eldorado do Sul",
"Torres",
"São Luiz Gonzaga",
"Gramado",
"Igrejinha",
"Palmeira das Missões",
"Portão",
"Caçapava do Sul",
"Garibaldi",
"Estrela",
"Candelária",
"Soledade",
"Santa Vitória do Palmar",
"Teutônia",
"Frederico Westphalen",
"Dois Irmãos",
"Flores da Cunha",
"Lagoa Vermelha",
"Triunfo",
"Jaguarão",
"Carlos Barbosa",
"Taquari",
"São José do Norte",
"Três Coroas",
"Nova Santa Rita",
"Vera Cruz",
"Encruzilhada do Sul",
"Nova Prata",
"Capão do Leão",
"Veranópolis",
"São Sebastião do Caí",
"Guaporé",
"Três Passos",
"Três de Maio",
"São Sepé",
"São Jerônimo",
"Tupanciretã",
"Quaraí",
"Sarandi",
"Ivoti",
"Encantado",
"Tapejara",
"São Francisco de Paula",
"São Marcos",
"Butiá",
"Rolante",
"Piratini",
"Nova Petrópolis",
"Imbé",
"Nova Hartz",
"Ibirubá",
"Arroio do Meio",
"Júlio de Castilhos",
]

if __name__ == '__main__':
    state = State.objects.filter(acronym="RS")
    cities = City.objects.filter(state=state)
    # city_names = {}
    # for city in cities:
    #     city_names[city.name] = True
    # for city in CIDADES:
    #     if city not in city_names:
    #         print(city)
    for city in cities:
        if city.name not in CIDADES:
            city.delete()
