import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bbsimples.settings')

import django
django.setup()

from bb_enxoval.models import City, State
from smart_selects.utils import unicode_sorter

CIDADES = [
"São Paulo",
"Guarulhos",
"Campinas",
"São Bernardo do Campo",
"Santo André",
"São José dos Campos",
"Osasco",
"Ribeirão Preto",
"Sorocaba",
"Mauá",
"São José do Rio Preto",
"Santos",
"Mogi das Cruzes",
"Diadema",
"Jundiaí",
"Piracicaba",
"Carapicuíba",
"Bauru",
"Itaquaquecetuba",
"São Vicente",
"Franca",
"Guarujá",
"Praia Grande",
"Taubaté",
"Limeira",
"Suzano",
"Taboão da Serra",
"Sumaré",
"Barueri",
"Embu das Artes",
"São Carlos",
"Indaiatuba",
"Cotia",
"Marília",
"Americana",
"Araraquara",
"Jacareí",
"Itapevi",
"Presidente Prudente",
"Hortolândia",
"Rio Claro",
"Araçatuba",
"Santa Bárbara d'Oeste",
"Ferraz de Vasconcelos",
"Francisco Morato",
"Itapecerica da Serra",
"Itu",
"Bragança Paulista",
"Pindamonhangaba",
"Itapetininga",
"São Caetano do Sul",
"Franco da Rocha",
"Mogi Guaçu",
"Jaú",
"Botucatu",
"Atibaia",
"Santana de Parnaíba",
"Araras",
"Cubatão",
"Valinhos",
"Sertãozinho",
"Ribeirão Pires",
"Jandira",
"Birigui",
"Catanduva",
"Barretos",
"Guaratinguetá",
"Votorantim",
"Tatuí",
"Várzea Paulista",
"Caraguatatuba",
"Itatiba",
"Salto",
"Poá",
"Ourinhos",
"Assis",
"Paulínia",
"Leme",
"Itanhaém",
"Caieiras",
"Mairiporã",
"Itapeva",
"Votuporanga",
"Caçapava",
"Mogi Mirim",
"São João da Boa Vista",
"Avaré",
"São Roque",
"Ubatuba",
"Lorena",
"Arujá",
"São Sebastião",
"Campo Limpo Paulista",
"Matão",
"Cruzeiro",
"Bebedouro",
"Ibiúna",
"Lins",
"Jaboticabal",
"Pirassununga",
"Vinhedo",
"Cajamar",
"Itapira",
"Amparo",
"Cosmópolis",
"Mococa",
"Fernandópolis",
"Embu-Guaçu",
"Lençóis Paulista",
"Peruíbe",
"Tupã",
"Penápolis",
"Batatais",
"Bertioga",
"Mirassol",
"Ibitinga",
"Nova Odessa",
"Boituva",
"Andradina",
"Monte Mor",
"Itupeva",
"Taquaritinga",
"Registro",
"Santa Isabel",
"Porto Ferreira",
"Piedade",
"São José do Rio Pardo",
"Capivari",
"Mongaguá",
"Jaguariúna",
"Olímpia",
"Porto Feliz",
"Artur Nogueira",
"Campos do Jordão",
"São Joaquim da Barra",
"Itararé",
"Vargem Grande Paulista",
"Monte Alto",
"Rio Grande da Serra",
"Jales",
"Cabreúva",
"Pontal",
"Capão Bonito",
"Santa Cruz do Rio Pardo",
"Cerquilho",
"Pedreira",
"Mairinque",
"Dracena",
"Louveira",
"Tremembé",
"Pederneiras",
"Paraguaçu Paulista",
"Garça",
"Salto de Pirapora",
"Espírito Santo do Pinhal",
"Presidente Epitácio",
"Serrana",
"Orlândia",
"Jardinópolis",
"Itápolis",
"Vargem Grande do Sul",
"Ituverava",
"Tietê",
"São Manuel",
"Guaíra",
"Novo Horizonte",
"Socorro",
"Presidente Venceslau",
"Promissão",
"Guariba",
"Américo Brasiliense",
"Pitangueiras",
"Agudos",
"Barra Bonita",
"Aparecida",
"José Bonifácio",
"Aguaí",
"Adamantina",
"Iperó",
"São Pedro",
"Cravinhos",
"Bariri",
"Ibaté",
"Rio das Pedras",
"Santa Cruz das Palmeiras",
"Ilhabela",
"Descalvado",
"São Miguel Arcanjo",
"Cachoeira Paulista",
"Osvaldo Cruz",
"Guararapes",
"Araçoiaba da Serra",
"Morro Agudo",
"Barrinha",
"Santa Fé do Sul",
"Biritiba-Mirim",
"Cândido Mota",
"Juquitiba",
"Iguape",
"Casa Branca",
"Igarapava",
"Rancharia",
"Piraju",
"Mirandópolis",
"Guararema",
"Cajati",
"Serra Negra",
"Pilar do Sul",
"Jarinu",
"Laranjal Paulista",
"Santa Rita do Passa Quatro",
"Conchal",
"Pirapozinho",
"Piracaia",
"Dois Córregos",
"Ilha Solteira",
"Itaí",
"Martinópolis",
"Santa Rosa de Viterbo",
"Pereira Barreto",
"Tanabi",
"Cajuru",
"Santa Gertrudes",
"Valparaíso",
"Pirajuí",
"Apiaí",
"Álvares Machado",
"Angatuba",
"Igaraçu do Tietê",
"Monte Aprazível",
"Brodowski",
"Bom Jesus dos Perdões",
"Brotas",
"Cordeirópolis",
"Potim",
"Tambaú",
"Iracemápolis",
"Taquarituba",
"Teodoro Sampaio",
"Santo Antônio de Posse",
"Palmital",
"Miguelópolis",
"Cunha",
"Pompéia",
"Lucélia",
"Guará",
"Bastos",
"Nova Granada",
"Araçariguama",
"Santo Anastácio",
"Guapiaçu",
"Pradópolis",
"Castilho",
"Junqueirópolis",
"Miracatu",
"Itatinga",
"Capela do Alto",
]

if __name__ == '__main__':
    state = State.objects.filter(acronym="SP")
    cities = City.objects.filter(state=state)
    # city_names = {}
    # for city in cities:
    #     city_names[city.name] = True
    # for city in CIDADES:
    #     if city not in city_names:
    #         print(city)
    for city in cities:
        if city.name not in CIDADES:
            city.delete()
