# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_enxoval', '0002_auto_20180113_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='climate_date_url',
            field=models.URLField(default='empty', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='climate_date_url',
            field=models.URLField(default='empty', unique=True),
            preserve_default=False,
        ),
    ]
