# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_enxoval', '0005_auto_20180113_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='acronym',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
