# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_enxoval', '0008_auto_20180211_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='rain',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_avg_c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_max_c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_min_c',
            field=models.FloatField(),
        ),
    ]
